import type { Customer, Booking, CallLog } from '@/lib/types'

const createCallLog = (
  id: string,
  duration: number,
  channel: 'VOICE' | 'WHATSAPP' | 'SMS' | 'WEB' | 'WALK_IN',
  transcript: string,
  intent: 'BOOKING' | 'INQUIRY' | 'COMPLAINT' | 'LEAD' | 'CANCEL' | 'RESCHEDULE' | 'OTHER',
  sentiment: 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE',
  daysAgo: number
): CallLog => {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  date.setHours(Math.floor(Math.random() * 10) + 9)
  date.setMinutes(Math.floor(Math.random() * 60))
  
  return {
    id,
    duration,
    channel,
    transcript,
    intent,
    bookingCreated: intent === 'BOOKING',
    leadCreated: intent === 'LEAD',
    sentiment,
    createdAt: date.toISOString(),
  }
}

const sampleTranscripts = {
  BOOKING: `AI: Hi, thanks for calling The Studio. How can I help you today?
Customer: Hi, I'd like to book an appointment for a balayage.
AI: Great choice! I have Jessica available on Friday at 2pm. Would that work for you?
Customer: Yes, that sounds perfect. Can I also get a trim at the same time?
AI: Unfortunately, a trim would be an additional 30 minutes. We can do a trim before the balayage starting at 11am. Would that work instead?
Customer: Yes, let's do that. 11am Friday.
AI: Perfect! I've booked you with Jessica for a trim at 11am and balayage at 12pm on Friday. You'll receive a confirmation shortly.`,
  
  INQUIRY: `AI: Hi, thanks for calling The Studio. How can I help you today?
Customer: I was wondering what your hours are on Saturdays?
AI: We're open Saturday from 9am to 8pm.
Customer: And do you do color corrections? I had a bad experience elsewhere.
AI: Yes, Jessica is our color specialist and she does color corrections. Would you like to schedule a consultation?
Customer: Maybe. How much does it cost?
AI: Color correction starts at $280 depending on the complexity. The best way to get an accurate quote is a consultation which is free.
Customer: Okay, I'll think about it. Thanks!`,
  
  RESCHEDULE: `AI: Hi, thanks for calling The Studio. How can I help you today?
Customer: Hi, I need to reschedule my appointment.
AI: Of course. Can I have your name or booking reference?
Customer: It's Sofia Chen, I was supposed to come in tomorrow at 2.
AI: I found your booking. What date and time would work better for you?
Customer: Any afternoon next week would be fine.
AI: I have Thursday at 3pm or Friday at 4pm available. Which works better?
Customer: Let's do Thursday at 3pm.
AI: Done! Your appointment is now Thursday at 3pm with Jessica for balayage. See you then!`,
}

export const customers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Sofia Chen',
    phone: '+1 (718) 555-1234',
    email: 'sofia.chen@email.com',
    preferredChannel: 'WHATSAPP',
    preferredStaffId: 'staff-2',
    preferredStaffName: 'Jessica Park',
    notes: 'VIP client - always book with Jessica when possible',
    consents: { essential: true, marketing: true, intelligence: true },
    totalBookings: 18,
    totalSpent: 1240,
    avgBookingValue: 69,
    lastBookingAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 240 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 1,
    churnRisk: 'LOW',
    ltv: 3200,
    rfmSegment: 'Champion',
    tags: ['VIP', 'Color Client', 'Jessica\'s Regular'],
    bookings: [],
    calls: [
      createCallLog('call-1', 245, 'VOICE', sampleTranscripts.BOOKING, 'BOOKING', 'POSITIVE', 3),
      createCallLog('call-2', 180, 'WHATSAPP', 'Customer inquiry about balayage maintenance', 'INQUIRY', 'NEUTRAL', 10),
    ],
    createdAt: new Date(Date.now() - 240 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-2',
    name: 'James Williams',
    phone: '+1 (718) 555-2345',
    email: 'james.w@email.com',
    preferredChannel: 'VOICE',
    preferredStaffId: 'staff-1',
    preferredStaffName: 'Marcus Silva',
    notes: 'Prefers short fades, always ask about design',
    consents: { essential: true, marketing: false, intelligence: false },
    totalBookings: 12,
    totalSpent: 540,
    avgBookingValue: 45,
    lastBookingAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 1,
    cancellationCount: 2,
    churnRisk: 'LOW',
    ltv: 1800,
    rfmSegment: 'Loyal',
    tags: ['Barber Client', 'Marcus\'s Regular'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-3',
    name: 'Aisha Johnson',
    phone: '+1 (718) 555-5678',
    email: 'aisha.j@email.com',
    preferredChannel: 'SMS',
    preferredStaffId: 'staff-4',
    preferredStaffName: 'Devon Chase',
    notes: 'Natural hair specialist client',
    consents: { essential: true, marketing: true, intelligence: false },
    totalBookings: 6,
    totalSpent: 380,
    avgBookingValue: 63,
    lastBookingAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 1,
    churnRisk: 'MEDIUM',
    ltv: 1200,
    rfmSegment: 'Potential',
    tags: ['Natural Hair', 'Devon\'s Client'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-4',
    name: 'Carlos Mendez',
    phone: '+1 (718) 555-4567',
    email: 'carlos.m@email.com',
    preferredChannel: 'VOICE',
    notes: 'First-time customer, high churn risk',
    consents: { essential: true, marketing: false, intelligence: false },
    totalBookings: 3,
    totalSpent: 105,
    avgBookingValue: 35,
    lastBookingAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 2,
    cancellationCount: 1,
    churnRisk: 'HIGH',
    ltv: 500,
    rfmSegment: 'At Risk',
    tags: ['High Churn Risk', 'No Show'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-5',
    name: 'Rachel Kim',
    phone: '+1 (718) 555-7777',
    email: 'rachel.k@email.com',
    preferredChannel: 'WEB',
    preferredStaffId: 'staff-2',
    preferredStaffName: 'Jessica Park',
    notes: 'Bride-to-be, booking wedding hair',
    consents: { essential: true, marketing: true, intelligence: true },
    totalBookings: 22,
    totalSpent: 2100,
    avgBookingValue: 95,
    lastBookingAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 0,
    churnRisk: 'LOW',
    ltv: 4500,
    rfmSegment: 'Champion',
    tags: ['VIP', 'Bride', 'Jessica\'s Regular'],
    bookings: [],
    calls: [
      createCallLog('call-3', 320, 'VOICE', sampleTranscripts.INQUIRY, 'INQUIRY', 'POSITIVE', 5),
    ],
    createdAt: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-6',
    name: 'Tyler Brooks',
    phone: '+1 (718) 555-6789',
    email: 'tyler.b@email.com',
    preferredChannel: 'WEB',
    preferredStaffId: 'staff-1',
    preferredStaffName: 'Marcus Silva',
    consents: { essential: true, marketing: true, intelligence: false },
    totalBookings: 8,
    totalSpent: 280,
    avgBookingValue: 35,
    lastBookingAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 1,
    churnRisk: 'LOW',
    ltv: 900,
    rfmSegment: 'Loyal',
    tags: ['Marcus\'s Regular'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-7',
    name: 'Maya Rodriguez',
    phone: '+1 (718) 555-7890',
    email: 'maya.r@email.com',
    preferredChannel: 'WHATSAPP',
    preferredStaffId: 'staff-2',
    preferredStaffName: 'Jessica Park',
    consents: { essential: true, marketing: true, intelligence: true },
    totalBookings: 15,
    totalSpent: 1800,
    avgBookingValue: 120,
    lastBookingAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 1,
    cancellationCount: 0,
    churnRisk: 'LOW',
    ltv: 2800,
    rfmSegment: 'Champion',
    tags: ['Color Client', 'VIP'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-8',
    name: 'David Kim',
    phone: '+1 (718) 555-8901',
    email: 'david.k@email.com',
    preferredChannel: 'WALK_IN',
    consents: { essential: true, marketing: false, intelligence: false },
    totalBookings: 4,
    totalSpent: 140,
    avgBookingValue: 35,
    lastBookingAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 0,
    churnRisk: 'MEDIUM',
    ltv: 600,
    rfmSegment: 'Potential',
    tags: ['Walk-in'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-9',
    name: 'Emma Wilson',
    phone: '+1 (718) 555-9012',
    email: 'emma.w@email.com',
    preferredChannel: 'SMS',
    preferredStaffId: 'staff-3',
    preferredStaffName: 'Priya Sharma',
    consents: { essential: true, marketing: true, intelligence: false },
    totalBookings: 9,
    totalSpent: 405,
    avgBookingValue: 45,
    lastBookingAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 1,
    churnRisk: 'LOW',
    ltv: 1200,
    rfmSegment: 'Loyal',
    tags: ['Nail Client', 'Priya\'s Regular'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-10',
    name: 'Ryan O\'Brien',
    phone: '+1 (718) 555-0123',
    email: 'ryan.o@email.com',
    preferredChannel: 'WEB',
    preferredStaffId: 'staff-1',
    preferredStaffName: 'Marcus Silva',
    consents: { essential: true, marketing: false, intelligence: false },
    totalBookings: 7,
    totalSpent: 175,
    avgBookingValue: 25,
    lastBookingAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 0,
    churnRisk: 'LOW',
    ltv: 800,
    rfmSegment: 'Loyal',
    tags: ['Beard Client', 'Marcus\'s Regular'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-11',
    name: 'Sarah Thompson',
    phone: '+1 (718) 555-1111',
    email: 'sarah.t@email.com',
    preferredChannel: 'WHATSAPP',
    preferredStaffId: 'staff-2',
    preferredStaffName: 'Jessica Park',
    consents: { essential: true, marketing: true, intelligence: true },
    totalBookings: 11,
    totalSpent: 1210,
    avgBookingValue: 110,
    lastBookingAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 160 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 0,
    cancellationCount: 0,
    churnRisk: 'LOW',
    ltv: 2400,
    rfmSegment: 'Loyal',
    tags: ['Color Client', 'VIP'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 160 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'cust-12',
    name: 'Lisa Chang',
    phone: '+1 (718) 555-2222',
    email: 'lisa.c@email.com',
    preferredChannel: 'SMS',
    preferredStaffId: 'staff-3',
    preferredStaffName: 'Priya Sharma',
    consents: { essential: true, marketing: true, intelligence: false },
    totalBookings: 5,
    totalSpent: 250,
    avgBookingValue: 50,
    lastBookingAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    firstBookingAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
    noShowCount: 1,
    cancellationCount: 0,
    churnRisk: 'MEDIUM',
    ltv: 900,
    rfmSegment: 'Potential',
    tags: ['Nail Client'],
    bookings: [],
    calls: [],
    createdAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const getCustomerById = (id: string) => customers.find(c => c.id === id)

export const getCustomerByPhone = (phone: string) => customers.find(c => c.phone === phone)

export const searchCustomers = (query: string) => {
  const lower = query.toLowerCase()
  return customers.filter(c => 
    c.name.toLowerCase().includes(lower) ||
    c.phone.includes(query) ||
    c.email?.toLowerCase().includes(lower)
  )
}