import type { Lead } from '@/lib/types'

export const leads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Emma Rodriguez',
    phone: '+1 (718) 555-9001',
    email: 'emma.r@email.com',
    status: 'NEW',
    urgency: 'HIGH',
    score: 78,
    channel: 'VOICE',
    inquiryText: 'Hi, I saw your Instagram and I\'m looking to book a balayage for my birthday. It\'s in 2 weeks. Do you have availability?',
    serviceInterest: 'Balayage',
    notes: 'Wedding anniversary coming up, wants to look special',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Jessica Park',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-2',
    name: 'Marcus Thompson',
    phone: '+1 (718) 555-9002',
    status: 'NEW',
    urgency: 'MEDIUM',
    score: 65,
    channel: 'WEB',
    inquiryText: 'Looking for a barber that does skin fades. Your reviews look great. Can I book for this weekend?',
    serviceInterest: "Men's Haircut",
    notes: '',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-3',
    name: 'Sophia Lee',
    phone: '+1 (718) 555-9003',
    email: 'sophia.l@email.com',
    status: 'NEW',
    urgency: 'LOW',
    score: 42,
    channel: 'WHATSAPP',
    inquiryText: 'Do you offer gel manicures on Sundays?',
    serviceInterest: 'Gel Manicure',
    notes: 'Inquired about Sunday hours',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-4',
    name: 'Jake Williams',
    phone: '+1 (718) 555-9004',
    status: 'CONTACTED',
    urgency: 'HIGH',
    score: 85,
    channel: 'VOICE',
    inquiryText: 'I need a haircut and beard trim before my job interview next Monday. It\'s kind of last minute but I\'m willing to pay extra for same-day if needed.',
    serviceInterest: 'Hair + Beard Combo',
    notes: 'Left voicemail, callback in 30 mins requested',
    assignedStaffId: 'staff-1',
    assignedStaffName: 'Marcus Silva',
    followUpAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-5',
    name: 'Olivia Brown',
    phone: '+1 (718) 555-9005',
    email: 'olivia.b@email.com',
    status: 'CONTACTED',
    urgency: 'MEDIUM',
    score: 72,
    channel: 'WEB',
    inquiryText: 'I\'m interested in highlights and a trim. What would be the total price and how long would it take?',
    serviceInterest: 'Highlights',
    notes: 'Sent pricing info via WhatsApp, awaiting response',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Jessica Park',
    followUpAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-6',
    name: 'Daniel Garcia',
    phone: '+1 (718) 555-9006',
    status: 'CONTACTED',
    urgency: 'LOW',
    score: 55,
    channel: 'SMS',
    inquiryText: 'How much for a kids haircut? My daughter is 8.',
    serviceInterest: "Kids Haircut",
    notes: 'Responded with pricing, no response yet',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-7',
    name: 'Isabella Martinez',
    phone: '+1 (718) 555-9007',
    email: 'isabella.m@email.com',
    status: 'QUALIFIED',
    urgency: 'HIGH',
    score: 92,
    channel: 'VOICE',
    inquiryText: 'My daughter needs a hair appointment for her quinceañera. We\'re looking for someone who can do elegant updos. Do you have someone who specializes in that?',
    serviceInterest: "Women's Cut + Style",
    notes: 'Very interested, wedding season booking. Budget $200-300. Needs consultation.',
    assignedStaffId: 'staff-4',
    assignedStaffName: 'Devon Chase',
    followUpAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-8',
    name: 'Ethan Davis',
    phone: '+1 (718) 555-9008',
    status: 'QUALIFIED',
    urgency: 'MEDIUM',
    score: 68,
    channel: 'WEB',
    inquiryText: 'I\'m moving to Brooklyn and need a new barber. I\'ve been getting fades for years, looking for someone who really knows their craft.',
    serviceInterest: "Men's Haircut",
    notes: 'Sent staff bios and availability. Wants to book recurring appointments.',
    assignedStaffId: 'staff-1',
    assignedStaffName: 'Marcus Silva',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-9',
    name: 'Mia Johnson',
    phone: '+1 (718) 555-9009',
    email: 'mia.j@email.com',
    status: 'BOOKED',
    urgency: 'HIGH',
    score: 95,
    channel: 'WHATSAPP',
    inquiryText: 'Saw your reviews and want to book a balayage with Jessica. I\'m available any Saturday in June.',
    serviceInterest: 'Balayage',
    notes: 'Converted to booking STU-0017',
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Jessica Park',
    convertedBookingId: 'booking-17',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-10',
    name: 'Liam Wilson',
    phone: '+1 (718) 555-9010',
    status: 'BOOKED',
    urgency: 'MEDIUM',
    score: 80,
    channel: 'VOICE',
    inquiryText: 'Need a quick beard trim before a date. Can you fit me in today?',
    serviceInterest: 'Beard Trim',
    notes: 'Quick turnaround, booked same day. Converted to booking STU-0008',
    assignedStaffId: 'staff-5',
    assignedStaffName: 'Alex Rivera',
    convertedBookingId: 'booking-8',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-11',
    name: 'Ava Smith',
    phone: '+1 (718) 555-9011',
    email: 'ava.s@email.com',
    status: 'LOST',
    urgency: 'MEDIUM',
    score: 45,
    channel: 'WEB',
    inquiryText: 'Thinking about trying a new salon. What\'s your cancellation policy?',
    serviceInterest: 'Classic Manicure',
    notes: 'Went to competitor. Asked about policies but never booked.',
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'lead-12',
    name: 'Noah Anderson',
    phone: '+1 (718) 555-9012',
    status: 'LOST',
    urgency: 'LOW',
    score: 30,
    channel: 'SMS',
    inquiryText: 'How far are you from the G train?',
    serviceInterest: "Men's Haircut",
    notes: 'No response after 3 days. Chose closer salon.',
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const getLeadById = (id: string) => leads.find(l => l.id === id)

export const getLeadsByStatus = (status: string) => leads.filter(l => l.status === status)

export const getNewLeadsCount = () => leads.filter(l => l.status === 'NEW').length