import type { Service } from '@/lib/types'

export const services: Service[] = [
  {
    id: 'svc-1',
    name: "Men's Haircut",
    description: 'Precision cut and style for men',
    category: 'HAIR',
    durationMin: 45,
    price: 35,
    staffIds: ['staff-1', 'staff-5'],
    isActive: true,
    isPopular: true,
    requiresDeposit: false,
    color: '#6C3CE1',
  },
  {
    id: 'svc-2',
    name: "Women's Cut + Style",
    description: 'Professional cut with styling and finishing',
    category: 'HAIR',
    durationMin: 60,
    price: 65,
    staffIds: ['staff-2', 'staff-4'],
    isActive: true,
    isPopular: true,
    requiresDeposit: false,
    color: '#6C3CE1',
  },
  {
    id: 'svc-3',
    name: 'Blowout',
    description: 'Professional blow dry and styling',
    category: 'HAIR',
    durationMin: 45,
    price: 55,
    staffIds: ['staff-2', 'staff-4'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#6C3CE1',
  },
  {
    id: 'svc-4',
    name: 'Silk Press',
    description: 'Heat styling for smooth, silky results',
    category: 'HAIR',
    durationMin: 90,
    price: 85,
    staffIds: ['staff-4'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#6C3CE1',
  },
  {
    id: 'svc-5',
    name: 'Balayage',
    description: 'Hand-painted color for natural, sun-kissed look',
    category: 'COLOR',
    durationMin: 180,
    price: 200,
    staffIds: ['staff-2'],
    isActive: true,
    isPopular: true,
    requiresDeposit: true,
    depositAmount: 50,
    color: '#EC4899',
  },
  {
    id: 'svc-6',
    name: 'Full Color',
    description: 'Single-process full head color',
    category: 'COLOR',
    durationMin: 120,
    price: 120,
    staffIds: ['staff-2'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#EC4899',
  },
  {
    id: 'svc-7',
    name: 'Highlights',
    description: 'Foil highlights throughout',
    category: 'COLOR',
    durationMin: 150,
    price: 150,
    staffIds: ['staff-2'],
    isActive: true,
    isPopular: false,
    requiresDeposit: true,
    depositAmount: 30,
    color: '#EC4899',
  },
  {
    id: 'svc-17',
    name: 'Color Correction',
    description: 'Complex color correction and repair',
    category: 'COLOR',
    durationMin: 240,
    price: 280,
    staffIds: ['staff-2'],
    isActive: true,
    isPopular: false,
    requiresDeposit: true,
    depositAmount: 100,
    color: '#EC4899',
  },
  {
    id: 'svc-21',
    name: 'Root Touch-Up',
    description: 'Color refresh for roots',
    category: 'COLOR',
    durationMin: 90,
    price: 80,
    staffIds: ['staff-2'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#EC4899',
  },
  {
    id: 'svc-8',
    name: 'Beard Trim',
    description: 'Shape and trim facial hair',
    category: 'BEARD',
    durationMin: 20,
    price: 20,
    staffIds: ['staff-1', 'staff-5'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#3B82F6',
  },
  {
    id: 'svc-9',
    name: 'Beard Shape-Up',
    description: 'Precision beard design and line-up',
    category: 'BEARD',
    durationMin: 30,
    price: 30,
    staffIds: ['staff-1', 'staff-5'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#3B82F6',
  },
  {
    id: 'svc-10',
    name: 'Hair + Beard Combo',
    description: 'Complete cut and beard service',
    category: 'BEARD',
    durationMin: 60,
    price: 55,
    staffIds: ['staff-1', 'staff-5'],
    isActive: true,
    isPopular: true,
    requiresDeposit: false,
    color: '#3B82F6',
  },
  {
    id: 'svc-11',
    name: 'Classic Manicure',
    description: 'Nail shaping, cuticle care, and polish',
    category: 'NAILS',
    durationMin: 45,
    price: 35,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#10B981',
  },
  {
    id: 'svc-12',
    name: 'Gel Manicure',
    description: 'Long-lasting gel polish application',
    category: 'NAILS',
    durationMin: 60,
    price: 50,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: true,
    requiresDeposit: false,
    color: '#10B981',
  },
  {
    id: 'svc-13',
    name: 'Classic Pedicure',
    description: 'Complete foot care and polish',
    category: 'NAILS',
    durationMin: 60,
    price: 45,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#10B981',
  },
  {
    id: 'svc-14',
    name: 'Gel Pedicure',
    description: 'Gel polish on feet with full pedicure',
    category: 'NAILS',
    durationMin: 75,
    price: 60,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#10B981',
  },
  {
    id: 'svc-15',
    name: 'Acrylic Full Set',
    description: 'Full acrylic nail extension',
    category: 'NAILS',
    durationMin: 90,
    price: 75,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#10B981',
  },
  {
    id: 'svc-16',
    name: 'Nail Art',
    description: 'Custom nail designs and art',
    category: 'NAILS',
    durationMin: 30,
    price: 25,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#10B981',
  },
  {
    id: 'svc-18',
    name: "Kids Haircut",
    description: 'Haircut for children 12 and under',
    category: 'HAIR',
    durationMin: 30,
    price: 25,
    staffIds: ['staff-1', 'staff-5'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#6C3CE1',
  },
  {
    id: 'svc-19',
    name: 'Braids',
    description: 'Protective braiding styles',
    category: 'HAIR',
    durationMin: 180,
    price: 120,
    staffIds: ['staff-4'],
    isActive: true,
    isPopular: false,
    requiresDeposit: true,
    depositAmount: 30,
    color: '#6C3CE1',
  },
  {
    id: 'svc-20',
    name: 'Natural Styles',
    description: 'Natural hair styling and care',
    category: 'HAIR',
    durationMin: 120,
    price: 90,
    staffIds: ['staff-4'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#6C3CE1',
  },
  {
    id: 'svc-22',
    name: 'Express Facial',
    description: 'Quick refresh facial for busy schedules',
    category: 'SPA',
    durationMin: 45,
    price: 65,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#F59E0B',
  },
  {
    id: 'svc-23',
    name: 'Deep Cleansing Facial',
    description: 'Thorough facial with extraction and mask',
    category: 'SPA',
    durationMin: 60,
    price: 90,
    staffIds: ['staff-3'],
    isActive: true,
    isPopular: false,
    requiresDeposit: false,
    color: '#F59E0B',
  },
]

export const getServiceById = (id: string) => services.find(s => s.id === id)

export const getServicesByCategory = (category: string) => services.filter(s => s.category === category)

export const getServicesByStaff = (staffId: string) => services.filter(s => s.staffIds.includes(staffId))