import type { StaffMember } from '@/lib/types'

export const staff: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Marcus Silva',
    roleTitle: 'Senior Stylist & Barber',
    bio: '10 years experience. Specialist in fades, tapers, and curly hair cuts.',
    avatarColor: '#6C3CE1',
    services: ['svc-1', 'svc-8', 'svc-9', 'svc-10'],
    workingHours: {
      monday: { open: '09:00', close: '19:00', closed: false },
      tuesday: { open: '09:00', close: '19:00', closed: false },
      wednesday: { open: '09:00', close: '19:00', closed: false },
      thursday: { open: '09:00', close: '19:00', closed: false },
      friday: { open: '09:00', close: '19:00', closed: false },
      saturday: { open: '09:00', close: '19:00', closed: false },
      sunday: { open: '10:00', close: '18:00', closed: true },
    },
    googleCalendarConnected: true,
    bookingsToday: 7,
    bookingsThisWeek: 34,
    utilizationRate: 88,
    totalRevenue: 12400,
    rating: 4.9,
    isActive: true,
  },
  {
    id: 'staff-2',
    name: 'Jessica Park',
    roleTitle: 'Color Specialist',
    bio: 'Certified colorist. Expert in balayage, highlights, and color correction.',
    avatarColor: '#EC4899',
    services: ['svc-5', 'svc-6', 'svc-7', 'svc-2', 'svc-3'],
    workingHours: {
      monday: { open: '09:00', close: '19:00', closed: true },
      tuesday: { open: '10:00', close: '19:00', closed: false },
      wednesday: { open: '10:00', close: '19:00', closed: false },
      thursday: { open: '10:00', close: '19:00', closed: false },
      friday: { open: '10:00', close: '19:00', closed: false },
      saturday: { open: '10:00', close: '19:00', closed: false },
      sunday: { open: '10:00', close: '18:00', closed: true },
    },
    googleCalendarConnected: true,
    bookingsToday: 5,
    bookingsThisWeek: 28,
    utilizationRate: 75,
    totalRevenue: 18900,
    rating: 4.8,
    isActive: true,
  },
  {
    id: 'staff-3',
    name: 'Priya Sharma',
    roleTitle: 'Nail Tech & Esthetician',
    bio: 'Licensed nail technician specializing in gel, acrylics, and nail art.',
    avatarColor: '#10B981',
    services: ['svc-11', 'svc-12', 'svc-13', 'svc-14', 'svc-15', 'svc-16'],
    workingHours: {
      monday: { open: '09:00', close: '18:00', closed: false },
      tuesday: { open: '09:00', close: '18:00', closed: false },
      wednesday: { open: '09:00', close: '18:00', closed: false },
      thursday: { open: '09:00', close: '18:00', closed: false },
      friday: { open: '09:00', close: '18:00', closed: false },
      saturday: { open: '09:00', close: '18:00', closed: false },
      sunday: { open: '10:00', close: '17:00', closed: false },
    },
    googleCalendarConnected: false,
    bookingsToday: 8,
    bookingsThisWeek: 42,
    utilizationRate: 92,
    totalRevenue: 9800,
    rating: 4.9,
    isActive: true,
  },
  {
    id: 'staff-4',
    name: 'Devon Chase',
    roleTitle: 'Stylist',
    bio: "Women's cut and styling specialist. Natural hair and protective styles.",
    avatarColor: '#F59E0B',
    services: ['svc-3', 'svc-4', 'svc-18', 'svc-19', 'svc-20'],
    workingHours: {
      monday: { open: '10:00', close: '18:00', closed: false },
      tuesday: { open: '10:00', close: '18:00', closed: false },
      wednesday: { open: '10:00', close: '18:00', closed: false },
      thursday: { open: '10:00', close: '18:00', closed: false },
      friday: { open: '10:00', close: '18:00', closed: false },
      saturday: { open: '09:00', close: '17:00', closed: false },
      sunday: { open: '10:00', close: '18:00', closed: true },
    },
    googleCalendarConnected: false,
    bookingsToday: 4,
    bookingsThisWeek: 22,
    utilizationRate: 60,
    totalRevenue: 8200,
    rating: 4.7,
    isActive: true,
  },
  {
    id: 'staff-5',
    name: 'Alex Rivera',
    roleTitle: 'Barber',
    bio: 'Precision cuts and classic barbering. Known for skin fades and designs.',
    avatarColor: '#3B82F6',
    services: ['svc-1', 'svc-8', 'svc-9', 'svc-17'],
    workingHours: {
      monday: { open: '10:00', close: '20:00', closed: true },
      tuesday: { open: '10:00', close: '20:00', closed: false },
      wednesday: { open: '10:00', close: '20:00', closed: false },
      thursday: { open: '10:00', close: '20:00', closed: false },
      friday: { open: '10:00', close: '20:00', closed: false },
      saturday: { open: '10:00', close: '20:00', closed: false },
      sunday: { open: '10:00', close: '20:00', closed: false },
    },
    googleCalendarConnected: false,
    bookingsToday: 6,
    bookingsThisWeek: 30,
    utilizationRate: 80,
    totalRevenue: 7600,
    rating: 4.8,
    isActive: true,
  },
]

export const getStaffById = (id: string) => staff.find(s => s.id === id)